info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T13:52:15.636Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T13:52:33.463Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T13:52:38.941Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T13:53:39.257Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T13:54:16.431Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T13:54:29.108Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T13:56:26.491Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-12T13:56:35.487Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T13:56:47.831Z"}
error: 
    status - 500 
    message - Error: data and salt arguments required
    at Object.hashSync (D:\Mysql\CURDOperations\node_modules\bcrypt\bcrypt.js:91:15)
    at _callee$ (D:\Mysql\CURDOperations\src\services\/user.service.js:20:33)
    at tryCatch (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newUser (D:\Mysql\CURDOperations\src\services\/user.service.js:19:21)
    at _callee3$ (D:\Mysql\CURDOperations\src\controllers\/user.controller.js:50:36)
    at tryCatch (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at newUser (D:\Mysql\CURDOperations\src\controllers\/user.controller.js:48:21)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Mysql\CURDOperations\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Mysql\CURDOperations\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at D:\Mysql\CURDOperations\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2023-06-12T13:56:50.785Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:06:14.946Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:11:31.677Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:34:11.339Z"}
error: uncaughtException: logger is not defined
ReferenceError: logger is not defined
    at D:\Mysql\CURDOperations\src\config\/database.js:34:5
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Mon Jun 12 2023 21:04:11 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":2169.093},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":159316,"external":1685164,"heapTotal":97009664,"heapUsed":47988688,"rss":136118272},"pid":11776,"uid":null,"version":"v18.16.0"},"stack":"ReferenceError: logger is not defined\n    at D:\\Mysql\\CURDOperations\\src\\config\\/database.js:34:5\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-06-12T15:34:11.438Z","trace":[{"column":5,"file":"D:\\Mysql\\CURDOperations\\src\\config\\/database.js","function":null,"line":34,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:04:11 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":2169.109},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196524,"external":1722412,"heapTotal":97009664,"heapUsed":48539320,"rss":136171520},"pid":11776,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:34:11.449Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:34:51.229Z"}
error: Could not connect to the database. Access denied for user 'Levono'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:34:51.298Z"}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:04:51 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":2208.968},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196500,"external":1722348,"heapTotal":97271808,"heapUsed":48602840,"rss":137170944},"pid":9100,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:34:51.302Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:38:23.546Z"}
error: Could not connect to the database. Access denied for user 'Levono'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:38:23.614Z"}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:08:23 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":2421.281},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196500,"external":1722348,"heapTotal":96485376,"heapUsed":48213760,"rss":136130560},"pid":12412,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:38:23.619Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:39:40.024Z"}
error: Could not connect to the database. Access denied for user 'Levono'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:39:40.094Z"}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:09:40 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":2497.765},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196500,"external":1722348,"heapTotal":97009664,"heapUsed":48316168,"rss":136802304},"pid":2088,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:39:40.099Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:39:47.615Z"}
error: Could not connect to the database. Access denied for user 'ROOT'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'ROOT'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'ROOT'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'ROOT'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:39:47.682Z"}
error: uncaughtException: Access denied for user 'ROOT'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'ROOT'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:09:47 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'ROOT'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'ROOT'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":2505.343},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196496,"external":1722344,"heapTotal":96485376,"heapUsed":48293064,"rss":136282112},"pid":6368,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'ROOT'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:39:47.687Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:39:50.516Z"}
error: Could not connect to the database. Access denied for user ''@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user ''@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user ''@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:39:50.592Z"}
error: uncaughtException: Access denied for user ''@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:09:50 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user ''@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user ''@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":2508.265},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":197146,"external":1722994,"heapTotal":97009664,"heapUsed":48257608,"rss":136912896},"pid":10576,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:39:50.597Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:39:55.348Z"}
info: Connected to the database. {"timestamp":"2023-06-12T15:39:55.435Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:40:12.755Z"}
info: Connected to the database. {"timestamp":"2023-06-12T15:40:12.858Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:48:25.774Z"}
error: Could not connect to the database. Access denied for user 'Levono'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:48:25.841Z"}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:18:25 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":3023.515},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196500,"external":1722348,"heapTotal":97271808,"heapUsed":48335880,"rss":136212480},"pid":5688,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:48:25.846Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:50:03.287Z"}
error: Could not connect to the database. Access denied for user 'Levono'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:50:03.376Z"}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:20:03 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":3121.046},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196500,"external":1722348,"heapTotal":98844672,"heapUsed":48940128,"rss":138612736},"pid":10520,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:50:03.382Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:50:23.538Z"}
error: Could not connect to the database. Access denied for user 'Levono'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:50:23.616Z"}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:20:23 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":3141.281},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196500,"external":1722348,"heapTotal":96747520,"heapUsed":48762192,"rss":136364032},"pid":7072,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:50:23.622Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:50:26.401Z"}
error: Could not connect to the database. Access denied for user 'Levono'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:50:26.481Z"}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:20:26 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":3144.156},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196500,"external":1722348,"heapTotal":97271808,"heapUsed":48611392,"rss":137064448},"pid":560,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:50:26.487Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:50:30.419Z"}
error: Could not connect to the database. Access denied for user 'Levono'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:50:30.498Z"}
error: uncaughtException: Access denied for user 'Levono'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\Mysql\CURDOperations\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Mon Jun 12 2023 21:20:30 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Levono'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":3148.171},"process":{"argv":["node","D:\\Mysql\\CURDOperations\\src\\index.js"],"cwd":"D:\\Mysql\\CURDOperations","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":196500,"external":1722348,"heapTotal":97271808,"heapUsed":48639144,"rss":136540160},"pid":9040,"uid":null,"version":"v18.16.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Levono'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2023-06-12T15:50:30.504Z","trace":[{"column":17,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\Mysql\\CURDOperations\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:50:45.737Z"}
info: Connected to the database. {"timestamp":"2023-06-12T15:50:45.829Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at D:\Mysql\CURDOperations\node_modules\jsonwebtoken\verify.js:171:19
    at getSecret (D:\Mysql\CURDOperations\node_modules\jsonwebtoken\verify.js:97:14)
    at Object.verify (D:\Mysql\CURDOperations\node_modules\jsonwebtoken\verify.js:101:10)
    at _callee$ (D:\Mysql\CURDOperations\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at userAuth (D:\Mysql\CURDOperations\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Mysql\CURDOperations\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:284:15
    at param (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:365:14)
    at param (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:421:3)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Mysql\CURDOperations\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at D:\Mysql\CURDOperations\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Mysql\CURDOperations\node_modules\raw-body\index.js:231:16)
    at done (D:\Mysql\CURDOperations\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Mysql\CURDOperations\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12) 
    url - /api/v1/users/1 
    method - GET 
    IP - ::1
   {"timestamp":"2023-06-12T15:51:48.684Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at D:\Mysql\CURDOperations\node_modules\jsonwebtoken\verify.js:171:19
    at getSecret (D:\Mysql\CURDOperations\node_modules\jsonwebtoken\verify.js:97:14)
    at Object.verify (D:\Mysql\CURDOperations\node_modules\jsonwebtoken\verify.js:101:10)
    at _callee$ (D:\Mysql\CURDOperations\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\Mysql\CURDOperations\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at userAuth (D:\Mysql\CURDOperations\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Mysql\CURDOperations\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:284:15
    at param (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:365:14)
    at param (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:421:3)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Mysql\CURDOperations\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Mysql\CURDOperations\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:328:13)
    at D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mysql\CURDOperations\node_modules\express\lib\router\index.js:280:10)
    at D:\Mysql\CURDOperations\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Mysql\CURDOperations\node_modules\raw-body\index.js:231:16)
    at done (D:\Mysql\CURDOperations\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Mysql\CURDOperations\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12) 
    url - /api/v1/users/2 
    method - GET 
    IP - ::1
   {"timestamp":"2023-06-12T15:52:57.793Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-06-12T15:53:25.783Z"}
info: Connected to the database. {"timestamp":"2023-06-12T15:53:25.867Z"}
